create table users
(
    id            int primary key generated by default as identity,
    nick_name     varchar(100) unique,
    phone_number  varchar(12) unique,
    registered_at timestamp default now() not null ,
    enabled       bool      default true not null
);