create table users
(
    id            int primary key generated by default as identity,
    nick_name     varchar(100) unique not null,
    phone_number  varchar(12) unique not null,
    registered_at timestamp default now() not null ,
    enabled       bool      default true not null
);

create table user_role
(
    user_id int not null,
    role varchar not null,
    constraint user_roles_idx unique (user_id, role),
    foreign key (user_id) references users(id) on delete cascade
);