drop table if exists users_adventurer;
drop table if exists adventurer;
drop table if exists role;
drop table if exists users;

create table users
(
    id            int generated by default as identity primary key,
    name          varchar                 not null unique,
    registered_at timestamp default now() not null
);

create table role
(
    user_id int     not null,
    role    varchar not null,
    constraint roles_idx unique (user_id, role),
    foreign key (user_id) references users (id) on delete cascade
);

create table hero
(
    id             int generated by default as identity primary key,
    user_id        int references users (id) on delete cascade,
    first_name     varchar(20)             not null,
    last_name      varchar(50)             not null,
    strength       int                     not null,
    agility        int                     not null,
    constitution   int                     not null,
    intelligence   int                     not null,
    wisdom         int                     not null,
    charisma       int                     not null,
    evil_good      int                     not null,
    chaotic_lawful int                     not null,
    money          int                     not null,
    playable       bool      default true  not null,
    created_at     timestamp default now() not null
);