drop table if exists users;
drop table if exists role;

create table users
(
    id    int generated by default as identity primary key,
    email varchar(100) not null unique,
    password varchar(100) not null
);

create table role
(
    user_id int not null,
    role varchar not null,
    constraint roles_idx unique (user_id, role),
    foreign key (user_id) references users (id) on delete cascade
);