drop table if exists hero;
drop table if exists role;
drop table if exists users;

create table users
(
    id            int generated by default as identity primary key,
    name          varchar                 not null unique,
    registered_at timestamp default now() not null
);

create table role
(
    user_id int     not null,
    role    varchar not null,
    constraint roles_idx unique (user_id, role),
    foreign key (user_id) references users (id) on delete cascade
);


create table hero
(
    id             int generated by default as identity primary key,
    user_id        int                     references users (id) on delete set null,
    first_name     varchar(20)             not null,
    last_name      varchar(50)             not null,
    created_at     timestamp default now() not null
);